import { type NextPage } from 'next';
import Head from 'next/head';
import { signIn, signOut, useSession } from 'next-auth/react';

const Home: NextPage = () => (
  <>
    <Head>
      <title>Expense Manager App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <AuthShowcase />
    </main>
  </>
);

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const handleAuthentication = async () => {
    if (sessionData) {
      await signOut();
    } else {
      await signIn();
    }
  };

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        // eslint-disable-next-line @typescript-eslint/no-misused-promises
        onClick={() => handleAuthentication()}
      >
        {sessionData ? 'Sign out' : 'Sign in'}
      </button>
    </div>
  );
};
